name: Run tests using Conda

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        
        with:
  activate-environment: ritudev
  environment-file: environment/python-package-conda.yml
  python-version: 3.9
  auto-activate-base: false

      - name: Install dependencies
        run: conda env update --file environment.yml --name base

      - name: Run tests
        run: |
          conda install pytest
          pytest || echo "No tests found or failed"
