name: Run tests using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          activate-environment: base
          auto-activate-base: true

      - name: Install dependencies from requirements.txt
        run: |
          conda install pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest || echo "No tests found or failed"
